package com.hospital.common.exception;

public enum ErrorCode {

    USER_NOT_FOUND,

    JOB_NOT_FOUND,
    EMPTY_QUEUE,
    Appointment_NOT_FOUND,
    DOCTOR_ALREADY_EXIST,
    PATIENT_NOT_FOUND,
    PATIENT_ALREADY_EXIST,
    SPECIALITY_NOT_FOUND,
    DOCTOR_NOT_FOUND,
    TIME_SLOTS_NOT_FOUND,
    USER_NOT_UNAUTHORIZED,
    TOKEN_NOT_VALID,
    BILLING_NOT_FOUND,
    INVALID_ID,
    DIAGNOSE_NOT_FOUND,
    MEDICAL_RECORD_NOT_FOUND,
    TREATMENT_NOT_FOUND,

    EMAIL_ALREADY_EXISTS,
    USER_ALREADY_EXIST,
    VALIDATION_ERROR,

    INTERNAL_SERVER_ERROR,

    ACCESS_DENIED
}